### PR TITLE
Move widget code into separate file

### PR DESCRIPTION
**Pull request by mwcraig**
The also subclasses from widgets.VBox instead of object and cleans up a couple little typos.  I'll do some more work on  it Thursday if you want to hold off on merging this (or I can open another PR).

### CODE REVIEW

**Comment by pllim** [comment]
Ops. For whatever reason, I did not get notified on this.

**Comment by pllim** [comment]
I am not sure if `core.py` should be in `examples`. I was envisioning the widget class to move to an installable module, and then notebook in the `example` can, say, do `from astrowidgets import SomeClass`. What do you think?

**Comment by mwcraig** [comment]
I agree; I think I can make that change later today (visiting family but looking like I'll have couple hours in the afternoon).

**Comment by mwcraig** [comment]
Closing, opened as separate PR in the main repo (sorry about that, should have asked first).

**Comment by pllim** [comment]
No problem. Thanks for cleaning it up!

**Pull request closed without merging**
